[package]
name = "relay"
version = "0.1.0"
description = "ReLay — Downloads, redefined"
authors = []
license = "MIT"
repository = ""
edition = "2021"
rust-version = "1.70"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.8", features = ["shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.31", features = ["bundled"] }
rusqlite_migration = "1.2"
dirs = "5"
reqwest = { version = "0.11", features = ["stream", "json"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "time", "macros", "process"] }
tokio-util = { version = "0.7" }
librqbit = { version = "8", default-features = false, features = ["default-tls"] }
anyhow = "1"
sha2 = "0.10"
yara = "0.31"
memmap2 = "0.9"
infer = "0.16"
goblin = "0.8"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
